### ISSUE TITLE
Consider exposing WARP as CL_DEVICE_TYPE_CPU

### ISSUE THREAD

**Issue by MathiasMagnus** [microsoft/OpenCLOn12#19]
I have already noted to @jenatali that exposing WARP as `CL_DEVICE_TYPE_GPU` is counterintuitive, I even tried running a [poll on Twitter](https://twitter.com/nagyegrimate/status/1336224820099420162?s=20) to see if I'm the only one thinking like it, but my Twitter penetration seems to have betrayed me. (That one vote out of 82 views did 100% agree with me though.) If slightly more votes would be useful, I could run it by the work-group and/or another poll posted by the OpenCLAPI Twitter user.

I understand that it's exposed as a GPU because "WARP for all intents and purposes behaves as a GPU", however OpenCL developers have explicit queries to find _where_ work enqueued to a device executes and expect the ground truth.

- In both single and multi-GPU systems creating a context for all devices of type `CL_DEVICE_TYPE_GPU` of a given context and all of a sudden CPU usage skyrockets, is bad experience and unexpected.
- OpenCL devs know, that if one wishes to use both the CPU and the GPU simultaneously, then they have to reserve some CPU cores for driver and app logic execution (using sub-devices). The bubbles in GPU exec created by CPU being busy executing device code is an overall net loss. (LuxMark can easily demonstrate this, as it doesn't employ this reservation.) However, the necessity of this reservation only becomes apparent to applications if the device is "properly" exposed as `CL_DEVICE_TYPE_CPU`.
- Similarly non-GPU devices loaded using MCDM instead of WDDM as mentione [here](https://github.com/microsoft/OpenCLOn12/pull/18#discussion_r611963537) are likely expected to be `CL_DEVICE_TYPE_ACCELERATOR` or `CL_DEVICE_TYPE_CUSTOM`, which kind of circumvents the issue, of users querying CPU/GPU devices and getting stuff which don't support images.

_(ps.: can't wait for OpenCLOn12 to land 3.0 support (SPIR-V support specifically). Keep up the good work!)_

**Comment by jenatali** [comment]
Hm, I think I agree with you here.

I'll probably add an environment variable to force one way or the other, with CPU as the default, as we like to use WARP as an isolation test to see if issues are caused by graphics drivers, and I wouldn't be surprised if some CL applications will only use GPUs.

I also agree with MCDM being `ACCELERATOR`, but if we're using DXGI instead of DXCore there's no way to distinguish between the two without initialization a D3D12 device, which would really slow down platform initialization, so I'll probably only make that change if we're using DXCore (which we should be on modern versions of Windows).

**Comment by BlohoJo** [comment]
CLonD3D12 always crashed for me until version 23. Finally working, after literally years, but the applications I need to use it need to see it as GPU, it won't allow CPU. Due to this ridiculous change, it now works, and I can't use it.

There is no reason to make this work as CPU only, this makes it so for ALL USERS, so now, NO ONE can use CLonD3D12 as a GPU. Maybe it will be too slow to be practical, or have other issues, but that is up to each and every INDIVIDUAL USER to decide. This needs to be an environment variable SET BY THE USER ACCORDING TO THEIR NEEDS.

There's MESA for OpenGL that works as a software renderer for applications that are looking for a GPU; There's WARP for DirectX that works as a software renderer for applications that are looking for a GPU; There's SwiftShader for Vulkan that works as a software renderer for applications that are looking for a GPU; but there's NO OpenCL software renderer for applications that are looking for a GPU. This was YEARS in the making as all it did was crash, and now it's finally working, only to be blocked by a simple configuration decision made because of this ticket, making it so that no one is allowed to use OpenCL as a GPU via CLonD3D12.

Please change this back, or if possible, implement a user configuration option (perhaps through an environment variable) that allows OpenCLon12/clon12compiler to be designated as Type: CPU or Type: GPU based on the individual user's needs.
