### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by eladmaimoni** [microsoft/OpenCLOn12#37]
Hi,

A few questions regarding this project, I could not find answers online.

- Can this project be used on a x64 systems with discrete GPUs (AMD / NVidia)?
- If so, What limitations a user can expect compared to the vendor implementation? 
- Specifically, will this OpenCL abstraction support accessing uchar buffers with byte granularity?

**Comment by MathiasMagnus** [comment]
While I'm not affiliated with the project, here are some answers I can provide:
- Yes, I've been using it that way for some time now.
- Mostly lower performance, depending on the task and device at hand. Also, slightly lower precision, but nothing severe enough to hurt conformance.
- I don't see a reason why it couldn't.

**Comment by eladmaimoni** [comment]
@MathiasMagnus thanks for the valuable info!

Can you share how exactly do you setup the environment? I can successfully build the project on my environment (Windows) but the test project can't find the CLOn12Compiler.dll at runtime.

BTW, the reason I asked about uchar buffer access is because hlsl is limited on that regard. I could not find how to access byte offset with hlsl.

**Comment by MathiasMagnus** [comment]
I haven't built it yet, because the compiler resides in Mesa and I wasn't dedicated enough to build Mesa myself. If you're only interested in using OpenCLOn12 then I'd suggest installing it from the [Microsoft Store](https://apps.microsoft.com/store/detail/opencl%E2%84%A2-and-opengl%C2%AE-compatibility-pack/9NQPSL29BFFF?hl=en-us&gl=US).

As for indexing an uchar array, just create a buffer with the appropriate size, initialize it like with any other type. Inside the kernel refer to it like a `global uchar* arr` kernel argument and index into it. OpenCL is a proper compute API so you can do pretty much whatever you can in C.

_Note: if installing it from the MS Store you don't see the platform, you need to build an OpenCL ICD Loader yourself, because it can only be loaded by a recent enough Loader. (One that is no older than 2 years-ish.) If the one inside System32 is too old, you'll have to make sure you copy your "custom" Loader next to every executable you build. I would discourage from overwriting the system Loader, because that's owned by your drivers._

**Comment by MathiasMagnus** [comment]
I'm not in front of a computer ATM, but if you look at an older GPUInfo.org [submission](http://opencl.gpuinfo.org/displayreport.php?id=60#deviceinfo) of mine from an RX580 laptop, and look at the [extensions](http://opencl.gpuinfo.org/displayreport.php?id=60#deviceextensions) it supports [`cl_khr_byte_addressable_store`](https://registry.khronos.org/OpenCL/sdk/1.0/docs/man/xhtml/cl_khr_byte_addressable_store.html) which is a ubiquitous extension, because it became a core spec feature in OpenCL 1.1.

**Comment by jenatali** [comment]
Yes, `cl_khr_byte_addressable_store` is supported, but it's not efficient. DXIL does not (yet) have support for 8-bit buffer accesses. Loads will be wider and then only the relevant channels will be used. Stores will be turned into a pair of atomics: one AND to set the relevant bits to 0, and then an OR to set the relevant bits to the new value.

**Comment by eladmaimoni** [comment]
@jenatali thanks for the info. I really hope DXIL will support such basic features in the near future, it is very essential to many compute usage scenarios. Do you know if there is a forum where I can request for such features to be supported?

**Comment by jenatali** [comment]
Sorry for the long delay on this.

> Do you know if there is a forum where I can request for such features to be supported?

https://github.com/microsoft/hlsl-specs is the new repository where a feature can be proposed to HLSL/DXIL. That said, I'm pretty sure this one is already on the backlog.

Since I believe the questions have been answered, I'll go ahead and close this, but please re-open or otherwise let me know if there's other questions.
