### ISSUE TITLE
Question about how to debug openclon12

### ISSUE THREAD

**Issue by peterer0625** [microsoft/OpenCLOn12#59]
Hello, we’d like to know how to debug openclon12.
We installed the pack https://apps.microsoft.com/detail/9nqpsl29bfff?hl=en-US&gl=US from MS store, and then uncovered an issue in openclon12.dll.
It looks like there is no simple way to just overlay a private build DLL file. Could you share the method?

**Comment by jenatali** [comment]
Right, there's no easy to way to replace to DLL in the app package.

For a local debugging/testing environment, you'll need:
* OpenCLOn12.dll built from this repository
* CLOn12Compiler.dll from [Mesa](https://gitlab.freedesktop.org/mesa/mesa). Can be built locally (though it's a pain due to LLVM and libclc dependencies), or prebuilt binaries can be downloaded from [mesa-dist-win](https://github.com/pal1000/mesa-dist-win/releases) or [Mesa CI](https://gitlab.freedesktop.org/mesa/mesa/-/pipelines) (e.g. [this one](https://gitlab.freedesktop.org/mesa/mesa/-/jobs/57445756/artifacts/browse/_install/bin/))
* DXIL.dll from [DirectXShaderCompiler](https://github.com/microsoft/DirectXShaderCompiler/releases)

Once you have these pieces, you can either use the [OpenCL registry keys](https://github.com/KhronosGroup/OpenCL-ICD-Loader?tab=readme-ov-file#registering-an-icd-on-windows) or [OpenCL environment variables](https://github.com/KhronosGroup/OpenCL-ICD-Loader?tab=readme-ov-file#table-of-debug-environment-variables), or you can typically just rename OpenCLOn12.dll to OpenCL.dll and put it next to the app.

Please do also report issues discovered.

**Comment by peterer0625** [comment]
Actually, the issue is gone with the newest commit, and we'd like to understand what's the root cause. If we uncover the issue is still there, we will report the issue.
